"""Public contracts for governed long-term memory."""

from .domain import (
    AuditRecord,
    EntityType,
    GovernanceAction,
    GovernanceCommand,
    GovernanceResult,
    MemoryDraft,
    MemoryRecord,
    MemoryStatus,
    RawEventDraft,
    RawEventReceipt,
    RecallItem,
    RecallQuery,
    RetentionPolicy,
    Scope,
    SourceRef,
    TrustLevel,
)
from .errors import (
    EntityDeleted,
    EntityNotFound,
    IdempotencyConflict,
    InvalidTransition,
    RepositoryCorruption,
    ScopeMismatch,
    TrueHeartError,
    TrustEscalation,
    ValidationError,
)

__all__ = [
    "AuditRecord",
    "EntityDeleted",
    "EntityNotFound",
    "EntityType",
    "GovernanceAction",
    "GovernanceCommand",
    "GovernanceResult",
    "IdempotencyConflict",
    "InvalidTransition",
    "MemoryDraft",
    "MemoryRecord",
    "MemoryStatus",
    "RawEventDraft",
    "RawEventReceipt",
    "RecallItem",
    "RecallQuery",
    "RepositoryCorruption",
    "RetentionPolicy",
    "Scope",
    "ScopeMismatch",
    "SourceRef",
    "TrueHeartError",
    "TrustEscalation",
    "TrustLevel",
    "ValidationError",
]
